### PR TITLE
Major API Improvements

### PR DESCRIPTION
**Pull request by chrisjsewell**

### CODE REVIEW

**Comment by choldgraf** [comment]
I take it this is us getting more creative with mistletoe structural changes?

**Comment by chrisjsewell** [comment]
Yes, it's improving the API along the lines outlined in the README (copied from https://github.com/ExecutableBookProject/MyST-Parser/issues/33#issuecomment-595223983_)

If you expand and read the commit messages; they are fairly detailed on what I have changed and why.

**Comment by choldgraf** [comment]
makes sense - I think this takes us a step closer to taking over maintenance of this thing full time, but maybe that's a necessary step

**Comment by chrisjsewell** [comment]
> makes sense - I think this takes us a step closer to taking over maintenance of this thing full time, but maybe that's a necessary step

Quite possibly, but as mentioned, I've ensured that I've documented in the commits what has changed and why. So, if the maintainer does re-surface, hopefully, he can understand what the proposed changes are.

Also, you end up supporting it in way or other *via* `myst-parser`. As you can see in  ExecutableBookProject/MyST-Parser#108, because of these update, I've been able to remove lots of code that was just patching mistletoe.

Ps, If you check out https://mistletoe-ebp.readthedocs.io/en/latest/api/index.html, its pretty nice now 😄 , and a lot like http://scorreia.com/software/panflute/code.html (it would probably be possible actually, to write a bridge between pandoc and mistletoe-ebp)

**Pull request merged**
